"""Exports: PDF inspection reports, PDF summary reports, CSV dumps, annotated-image ZIPs."""
from __future__ import annotations

import csv
import io
import os
import zipfile

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import Image as RLImage
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from waferguard.api.services import filestore
from waferguard.taxonomy import PROBABLE_CAUSES, display_name

CSV_FIELDS = ["id", "created_at", "operator", "equipment_id", "lot_id", "wafer_id", "recipe", "source", "filename",
              "label", "confidence", "severity", "needs_review", "fail_ratio", "die_count", "n_regions",
              "input_domain", "model_version", "model_variant", "latency_ms", "review_label", "reviewed_by", "reviewed_at"]

_SEV_COL = {"Critical": colors.HexColor("#E63946"), "Major": colors.HexColor("#F4A261"),
            "Minor": colors.HexColor("#E9C46A"), "None": colors.HexColor("#6DBE8C")}


def _table(rows, widths=None, header=True):
    t = Table(rows, colWidths=widths, hAlign="LEFT")
    style = [("FONT", (0, 0), (-1, -1), "Helvetica", 9), ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
             ("VALIGN", (0, 0), (-1, -1), "TOP"), ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]
    if header:
        style += [("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1F3A4D")), ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                  ("FONT", (0, 0), (-1, 0), "Helvetica-Bold", 9)]
    t.setStyle(TableStyle(style))
    return t


def inspection_pdf(insp, generated_by: str, guide: dict | None = None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm,
                            title=f"Inspection {insp.id}")
    ss = getSampleStyleSheet()
    el = [Paragraph("Wafer inspection report", ss["Title"]),
          Paragraph(f"Inspection {insp.id} &nbsp; generated by {generated_by}", ss["Normal"]), Spacer(1, 6)]
    final = insp.review_label or insp.label
    meta = [["Field", "Value"],
            ["Timestamp (UTC)", insp.created_at.strftime("%Y-%m-%d %H:%M:%S")],
            ["Operator", insp.operator], ["Equipment", insp.equipment_id or "-"], ["Lot", insp.lot_id or "-"],
            ["Wafer", insp.wafer_id or "-"], ["Recipe / step", insp.recipe or "-"], ["Source", insp.source],
            ["Model", f"{insp.model_version} ({insp.model_variant})"], ["Input domain", insp.input_domain or "-"]]
    el += [_table(meta, [45 * mm, 120 * mm]), Spacer(1, 8)]
    res = [["Result", "Value"],
           ["Classification", f"{display_name(insp.label)} ({insp.confidence:.1%})"],
           ["Severity", insp.severity], ["Fail-die ratio", f"{insp.fail_ratio:.2%} of {insp.die_count} px/dies"],
           ["Needs review", "yes" if insp.needs_review else "no"],
           ["Engineer review", f"{display_name(insp.review_label)} by {insp.reviewed_by}" if insp.review_label else "-"],
           ["Final disposition label", display_name(final)]]
    t = _table(res, [45 * mm, 120 * mm])
    t.setStyle(TableStyle([("BACKGROUND", (1, 2), (1, 2), _SEV_COL.get(insp.severity, colors.white))]))
    el += [t, Spacer(1, 8)]
    img = filestore.get(insp.annotated_path)
    if img:
        el += [RLImage(io.BytesIO(img), width=85 * mm, height=85 * mm, kind="proportional"), Spacer(1, 6)]
    probs = sorted((insp.probabilities or {}).items(), key=lambda kv: -kv[1])
    el += [Paragraph("Class probabilities", ss["Heading3"]),
           _table([["Class", "Probability"]] + [[display_name(k), f"{v:.2%}"] for k, v in probs], [60 * mm, 40 * mm])]
    if insp.regions:
        el += [Paragraph("Localized defect regions", ss["Heading3"]),
               _table([["#", "BBox x,y,w,h (px)", "Failing px", "Share of wafer"]] +
                      [[str(i + 1), ", ".join(map(str, r["bbox"])), str(r["area_px"]), f"{r['area_frac']:.2%}"]
                       for i, r in enumerate(insp.regions[:15])])]
    if guide and guide.get("causes") is not None and final != "none":
        body = ss["BodyText"]
        el += [Paragraph("How this defect forms", ss["Heading3"]), Paragraph(guide["mechanism"], body)]
        for n in guide.get("recurrence_notes", []):
            el.append(Paragraph(f"<b>Recurrence:</b> {n}", body))
        if guide["causes"]:
            cell = ss["BodyText"].clone("cell", fontSize=8.5, leading=10.5)
            el += [Paragraph("Likely causes and how to confirm them", ss["Heading3"]),
                   _table([["Likely cause", "Process area", "What to check"]] +
                          [[Paragraph(c["cause"], cell), Paragraph(c["area"], cell), Paragraph(c["check"], cell)]
                           for c in guide["causes"]], [55 * mm, 32 * mm, 83 * mm])]
        for key, title in (("immediate", "Do now"), ("investigate", "Investigate"), ("prevent", "Prevent recurrence")):
            items = guide["actions"].get(key) or []
            if items:
                el.append(Paragraph(title, ss["Heading3"]))
                el += [Paragraph(f"{i + 1}. {t}", body) for i, t in enumerate(items)]
        el += [Spacer(1, 4), Paragraph(f"<i>{guide['disclaimer']}</i>", ss["Italic"])]
    else:
        causes = PROBABLE_CAUSES.get(final, [])
        if causes:
            el += [Paragraph("Probable process causes (to verify)", ss["Heading3"])] + [Paragraph(f"&bull; {c}", ss["Normal"]) for c in causes]
    doc.build(el)
    return buf.getvalue()


def summary_pdf(title: str, filters: dict, stats: dict, rows: list, generated_by: str) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=15 * mm, rightMargin=15 * mm, topMargin=15 * mm, title=title)
    ss = getSampleStyleSheet()
    el = [Paragraph(title, ss["Title"]),
          Paragraph("Filters: " + (", ".join(f"{k}={v}" for k, v in filters.items() if v) or "none") +
                    f" &nbsp; generated by {generated_by}", ss["Normal"]), Spacer(1, 8)]
    cap = stats.get("capability", {})
    kv = [["Metric", "Value"], ["Wafers inspected", str(stats.get("total", 0))],
          ["Defective wafers", f"{stats.get('defective', 0)} ({stats.get('defect_rate', 0):.1%})"],
          ["Critical / Major / Minor", " / ".join(str(stats.get('by_severity', {}).get(s, 0)) for s in ("Critical", "Major", "Minor"))],
          ["Mean fail-die ratio", f"{cap.get('mean', 0) or 0:.2%}"],
          ["Cpk / Ppk (fail ratio, USL %.0f%%)" % (100 * (cap.get("usl") or 0)),
           f"{_f(cap.get('cpk'))} / {_f(cap.get('ppk'))} ({cap.get('rating', '-')})"]]
    el += [_table(kv, [70 * mm, 100 * mm]), Spacer(1, 8)]
    if stats.get("pareto"):
        el += [Paragraph("Defect Pareto", ss["Heading3"]),
               _table([["Pattern", "Count", "Share", "Cumulative"]] +
                      [[display_name(p["label"]), str(p["count"]), f"{p['share']:.1%}", f"{p['cumulative']:.1%}"] for p in stats["pareto"]])]
    el += [Spacer(1, 8), Paragraph(f"Inspections (latest {min(len(rows), 200)})", ss["Heading3"]),
           _table([["Time (UTC)", "Lot", "Wafer", "Equip.", "Label", "Conf.", "Severity"]] +
                  [[r.created_at.strftime("%m-%d %H:%M"), r.lot_id or "-", (r.wafer_id or "-")[:18], r.equipment_id or "-",
                    display_name(r.review_label or r.label), f"{r.confidence:.0%}", r.severity] for r in rows[:200]])]
    doc.build(el)
    return buf.getvalue()


def _f(v):
    return "-" if v is None else f"{v:.2f}"


def inspections_csv(rows) -> str:
    out = io.StringIO()
    w = csv.DictWriter(out, CSV_FIELDS)
    w.writeheader()
    for r in rows:
        w.writerow({"id": r.id, "created_at": r.created_at.isoformat(), "operator": r.operator,
                    "equipment_id": r.equipment_id, "lot_id": r.lot_id, "wafer_id": r.wafer_id, "recipe": r.recipe,
                    "source": r.source, "filename": r.filename, "label": r.label, "confidence": round(r.confidence, 5),
                    "severity": r.severity, "needs_review": r.needs_review, "fail_ratio": round(r.fail_ratio, 5),
                    "die_count": r.die_count, "n_regions": len(r.regions or []), "input_domain": r.input_domain,
                    "model_version": r.model_version, "model_variant": r.model_variant,
                    "latency_ms": round(r.latency_ms, 2), "review_label": r.review_label, "reviewed_by": r.reviewed_by,
                    "reviewed_at": r.reviewed_at.isoformat() if r.reviewed_at else ""})
    return out.getvalue()


def images_zip(rows, include_masks: bool = True) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr("inspections.csv", inspections_csv(rows))
        for r in rows:
            stem = f"{r.lot_id or 'nolot'}_{r.wafer_id or r.id}_{r.review_label or r.label}".replace("/", "-")
            ann = filestore.get(r.annotated_path)
            if ann:
                z.writestr(f"annotated/{stem}.png", ann)
            msk = filestore.get(r.mask_path) if include_masks else None
            if msk:
                z.writestr(f"masks/{stem}_mask.png", msk)
    return buf.getvalue()
